export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen py-16 px-4 mt-16">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-6">
          Privacy Policy
        </h1>
        <p className="text-gray-400 mb-8">Last updated: February 22, 2025</p>

        <div className="space-y-8 text-gray-300">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              1. Introduction
            </h2>
            <p>
              Welcome to OSCAR (&quot;we,&quot; &quot;our,&quot; or
              &quot;us&quot;). We are committed to protecting your privacy. This
              Privacy Policy explains how we collect, use, disclose, and
              safeguard your information when you use our voice note
              application.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              2. Information We Collect
            </h2>
            <h3 className="text-xl font-semibold text-white mb-3">
              2.1 Personal Information
            </h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Email address (for account creation and authentication)</li>
              <li>Name (if provided during OAuth authentication)</li>
              <li>Profile information from OAuth providers (Google, etc.)</li>
            </ul>

            <h3 className="text-xl font-semibold text-white mb-3 mt-4">
              2.2 Voice and Content Data
            </h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                Voice recordings (temporarily processed, not permanently stored
                as audio)
              </li>
              <li>Transcribed text from your voice notes</li>
              <li>Formatted notes and titles generated by AI</li>
              <li>Custom vocabulary entries you create</li>
              <li>Notes you save, star, or edit</li>
            </ul>

            <h3 className="text-xl font-semibold text-white mb-3 mt-4">
              2.3 Payment Information
            </h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                Payment and billing information processed through Razorpay
              </li>
              <li>Subscription status and billing cycle information</li>
              <li>We do not store credit card details on our servers</li>
            </ul>

            <h3 className="text-xl font-semibold text-white mb-3 mt-4">
              2.4 Usage Data
            </h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Recording usage statistics (count, duration)</li>
              <li>Feature usage and interaction data</li>
              <li>Feedback on AI formatting quality</li>
              <li>Device and browser information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              3. How We Use Your Information
            </h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>To provide and maintain our voice note service</li>
              <li>To process voice recordings into formatted text using AI</li>
              <li>To manage your account and subscription</li>
              <li>To process payments through Razorpay</li>
              <li>To enforce usage limits based on your subscription tier</li>
              <li>To improve our AI formatting algorithms</li>
              <li>To send important service updates and notifications</li>
              <li>To provide customer support</li>
              <li>To comply with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              4. Third-Party Services
            </h2>
            <p className="mb-4">We use the following third-party services:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong className="text-white">Supabase:</strong>{" "}
                Authentication, database, and data storage
              </li>
              <li>
                <strong className="text-white">DeepSeek:</strong> AI processing
                for text formatting, translation, and title generation
              </li>
              <li>
                <strong className="text-white">Razorpay:</strong> Payment
                processing and subscription management
              </li>
              <li>
                <strong className="text-white">OAuth Providers:</strong> Google
                and other authentication providers
              </li>
            </ul>
            <p className="mt-4">
              Each service has its own privacy policy governing their use of
              your data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              5. Voice Data Processing
            </h2>
            <p className="mb-4">
              <strong className="text-white">Important:</strong> Your voice
              recordings are processed in real-time to generate text
              transcriptions. We do not permanently store your audio recordings
              on our servers. The audio is:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Processed locally in your browser when possible</li>
              <li>Converted to text immediately</li>
              <li>Discarded after transcription is complete</li>
              <li>Only the resulting text is saved to your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              6. Data Retention
            </h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong className="text-white">Notes:</strong> Stored until you
                delete them
              </li>
              <li>
                <strong className="text-white">Account Data:</strong> Retained
                while your account is active
              </li>
              <li>
                <strong className="text-white">Usage Statistics:</strong>{" "}
                Retained for service improvement
              </li>
              <li>
                <strong className="text-white">Payment Records:</strong>{" "}
                Retained as required by law
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              7. Your Rights
            </h2>
            <p className="mb-4">You have the right to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Access your personal data</li>
              <li>Correct inaccurate data</li>
              <li>Delete your data and account</li>
              <li>Export your notes and data</li>
              <li>Withdraw consent for data processing</li>
              <li>Object to certain data processing activities</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              8. Data Security
            </h2>
            <p>
              We implement appropriate technical and organizational measures to
              protect your data, including encryption, secure authentication,
              and access controls. However, no method of transmission over the
              Internet is 100% secure.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              9. International Data Transfers
            </h2>
            <p>
              Your data may be transferred to and processed in countries other
              than your country of residence. We ensure appropriate safeguards
              are in place for such transfers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              10. Children&apos;s Privacy
            </h2>
            <p>
              Our service is not intended for children under 13. We do not
              knowingly collect data from children under 13.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              11. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will
              notify you of any changes by posting the new policy on this page
              and updating the &quot;Last updated&quot; date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">
              12. Contact Us
            </h2>
            <p>
              If you have questions about this Privacy Policy, please contact us
              through the settings page or at the contact information provided
              in our application.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
