"use client";

import { useState } from "react";
import {
  Users,
  Calendar,
  ChevronDown,
  ChevronUp,
  MonitorPlay,
  Mic2,
  Copy,
  Mail,
  Pencil,
  MoreVertical,
  Trash2,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";
import { MeetingNotesEditor } from "./MeetingNotesEditor";
import { MeetingMetadataEditor } from "./MeetingMetadataEditor";
import { DeleteMeetingDialog } from "./DeleteMeetingDialog";
import type {
  SavedMeetingRecord,
  MeetingTranscriptSegment,
  MeetingAttendee,
  MeetingTypeHint,
} from "@oscar/shared/types";

// ── helpers ──────────────────────────────────────────────────────────────────

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function meetingTypeBadge(hint: string) {
  const map: Record<string, { label: string; cls: string }> = {
    discovery: { label: "Discovery", cls: "bg-cyan-500/15 text-cyan-300" },
    "1on1": { label: "1-on-1", cls: "bg-cyan-500/15 text-cyan-300" },
    standup: { label: "Stand-up", cls: "bg-slate-500/15 text-slate-300" },
    general: { label: "General", cls: "bg-cyan-500/15 text-cyan-300" },
    auto: { label: "Meeting", cls: "bg-slate-500/15 text-slate-300" },
  };
  const { label, cls } = map[hint] ?? map.auto;
  return (
    <span
      className={`inline-flex items-center px-2 py-0.5 rounded-full text-[0.7rem] font-medium ${cls}`}
    >
      {label}
    </span>
  );
}

function TranscriptSegment({ seg }: { seg: MeetingTranscriptSegment }) {
  const isSpeaker = seg.speaker.source === "speaker";
  return (
    <div className={`flex gap-3 ${isSpeaker ? "flex-row-reverse" : ""}`}>
      <div className="flex-shrink-0 mt-0.5">
        {isSpeaker ? (
          <MonitorPlay size={14} className="text-cyan-400" />
        ) : (
          <Mic2 size={14} className="text-slate-400" />
        )}
      </div>
      <p
        className={`text-sm leading-relaxed max-w-[85%] ${
          isSpeaker ? "text-right text-slate-300" : "text-slate-300"
        }`}
      >
        <span className="text-[0.65rem] text-slate-500 mr-1.5">
          {seg.speaker.diarization_label ?? (isSpeaker ? "Them" : "Me")}
        </span>
        {seg.text}
      </p>
    </div>
  );
}

// ── types ────────────────────────────────────────────────────────────────────

interface MeetingCardProps {
  meeting: SavedMeetingRecord;
  onUpdate: (
    id: string,
    updates: Partial<SavedMeetingRecord>
  ) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
}

// ── component ────────────────────────────────────────────────────────────────

export function MeetingCard({ meeting, onUpdate, onDelete }: MeetingCardProps) {
  const { toast } = useToast();
  const [expanded, setExpanded] = useState(false);
  const [editingNotes, setEditingNotes] = useState(false);
  const [editingMyNotes, setEditingMyNotes] = useState(false);
  const [editingMetadata, setEditingMetadata] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  const hasTranscript = meeting.transcriptSegments.length > 0;
  const hasNotes = !!meeting.notesMarkdown?.trim();
  const hasMyNotes = !!meeting.myNotesMarkdown?.trim();

  async function handleCopy(text: string) {
    await navigator.clipboard.writeText(text);
    toast({ title: "Copied!", description: "Notes copied to clipboard." });
  }

  function handleEmail() {
    const emails = meeting.attendeesFull
      .map((a) => a.email?.trim())
      .filter(Boolean)
      .join(",");
    const subject = encodeURIComponent(
      `Meeting Notes: ${meeting.meetingTitle || "Untitled"}`
    );
    const body = encodeURIComponent(
      `Hi,\n\nPlease find the meeting notes below.\n\n---\n\n${meeting.notesMarkdown || ""}\n\n---\n\nGenerated by OSCAR`
    );
    window.open(`mailto:${emails}?subject=${subject}&body=${body}`);
  }

  async function handleSaveNotes(value: string) {
    await onUpdate(meeting.id, { notesMarkdown: value });
    setEditingNotes(false);
    toast({ title: "Saved", description: "Meeting notes updated." });
  }

  async function handleSaveMyNotes(value: string) {
    await onUpdate(meeting.id, { myNotesMarkdown: value });
    setEditingMyNotes(false);
    toast({ title: "Saved", description: "Personal notes updated." });
  }

  async function handleSaveMetadata(data: {
    meetingTitle: string;
    attendeesCompact: string;
    attendeesFull: MeetingAttendee[];
    meetingTypeHint: MeetingTypeHint;
  }) {
    await onUpdate(meeting.id, data);
    setEditingMetadata(false);
    toast({ title: "Saved", description: "Meeting details updated." });
  }

  async function handleDelete() {
    setIsDeleting(true);
    try {
      await onDelete(meeting.id);
      toast({ title: "Deleted", description: "Meeting removed." });
    } finally {
      setIsDeleting(false);
      setDeleteOpen(false);
    }
  }

  return (
    <>
      <article className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden transition-all duration-200 hover:border-slate-700">
        {/* Card header */}
        <div className="flex items-start gap-2">
          <button
            onClick={() => setExpanded((v) => !v)}
            className="flex-1 text-left p-5 sm:p-6 flex items-start justify-between gap-4 group hover:bg-slate-800/50 transition-colors duration-150"
            aria-expanded={expanded}
          >
            <div className="min-w-0 flex-1 space-y-2">
              <div className="flex flex-wrap items-center gap-2">
                {meetingTypeBadge(meeting.meetingTypeHint)}
              </div>
              <h2 className="text-base sm:text-lg font-semibold text-white leading-snug">
                {meeting.meetingTitle || "Untitled Meeting"}
              </h2>
              <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-slate-400">
                <span className="flex items-center gap-1.5">
                  <Calendar size={13} className="flex-shrink-0" />
                  {formatDate(meeting.startedAt)}
                </span>
                {meeting.attendeesCompact && (
                  <span className="flex items-center gap-1.5 truncate max-w-[220px]">
                    <Users size={13} className="flex-shrink-0" />
                    {meeting.attendeesCompact}
                  </span>
                )}
              </div>
            </div>
            <div className="flex-shrink-0 text-slate-500 group-hover:text-slate-300 transition-colors mt-1">
              {expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
            </div>
          </button>

          {/* Actions dropdown */}
          <div className="pt-5 pr-3 sm:pr-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button className="p-1.5 text-slate-500 hover:text-slate-300 rounded-lg hover:bg-slate-800 transition-colors duration-150" aria-label="Meeting actions">
                  <MoreVertical size={16} />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent
                align="end"
                className="bg-slate-800 border-slate-700"
              >
                <DropdownMenuItem
                  onClick={() => {
                    setExpanded(true);
                    setEditingMetadata(true);
                  }}
                  className="text-slate-300 focus:text-white focus:bg-slate-700 cursor-pointer"
                >
                  <Pencil size={14} className="mr-2" />
                  Edit details
                </DropdownMenuItem>
                {hasNotes && (
                  <DropdownMenuItem
                    onClick={() => handleCopy(meeting.notesMarkdown)}
                    className="text-slate-300 focus:text-white focus:bg-slate-700 cursor-pointer"
                  >
                    <Copy size={14} className="mr-2" />
                    Copy notes
                  </DropdownMenuItem>
                )}
                {hasNotes && (
                  <DropdownMenuItem
                    onClick={handleEmail}
                    className="text-slate-300 focus:text-white focus:bg-slate-700 cursor-pointer"
                  >
                    <Mail size={14} className="mr-2" />
                    Email notes
                  </DropdownMenuItem>
                )}
                <DropdownMenuItem
                  onClick={() => setDeleteOpen(true)}
                  className="text-red-400 focus:text-red-300 focus:bg-slate-700 cursor-pointer"
                >
                  <Trash2 size={14} className="mr-2" />
                  Delete
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>

        {/* Metadata editor */}
        {expanded && editingMetadata && (
          <MeetingMetadataEditor
            title={meeting.meetingTitle}
            attendees={meeting.attendeesFull}
            typeHint={meeting.meetingTypeHint}
            onSave={handleSaveMetadata}
            onCancel={() => setEditingMetadata(false)}
          />
        )}

        {/* Expandable body */}
        {expanded && (
          <div className="border-t border-slate-800 divide-y divide-slate-800">
            {/* AI-generated meeting notes */}
            <section className="p-5 sm:p-6 space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-cyan-400">
                  Meeting Notes
                </h3>
                <div className="flex items-center gap-1">
                  {hasNotes && !editingNotes && (
                    <>
                      <button
                        onClick={() => handleCopy(meeting.notesMarkdown)}
                        className="p-1.5 text-slate-500 hover:text-slate-300 rounded-lg transition-colors duration-150"
                        title="Copy"
                        aria-label="Copy notes"
                      >
                        <Copy size={14} />
                      </button>
                      <button
                        onClick={handleEmail}
                        className="p-1.5 text-slate-500 hover:text-slate-300 rounded-lg transition-colors duration-150"
                        title="Email"
                        aria-label="Email notes"
                      >
                        <Mail size={14} />
                      </button>
                    </>
                  )}
                  {!editingNotes && (
                    <button
                      onClick={() => setEditingNotes(true)}
                      className="p-1.5 text-slate-500 hover:text-slate-300 rounded-lg transition-colors duration-150"
                      title="Edit"
                      aria-label="Edit meeting notes"
                    >
                      <Pencil size={14} />
                    </button>
                  )}
                </div>
              </div>
              {editingNotes ? (
                <MeetingNotesEditor
                  value={meeting.notesMarkdown}
                  onSave={handleSaveNotes}
                  onCancel={() => setEditingNotes(false)}
                />
              ) : hasNotes ? (
                <div className="prose prose-sm prose-invert max-w-none text-slate-300 whitespace-pre-wrap leading-relaxed">
                  {meeting.notesMarkdown}
                </div>
              ) : (
                <p className="text-sm text-slate-500 italic">
                  No AI notes yet. Click edit to add notes.
                </p>
              )}
            </section>

            {/* My personal notes */}
            <section className="p-5 sm:p-6 space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-slate-300">
                  My Notes
                </h3>
                {!editingMyNotes && (
                  <button
                    onClick={() => setEditingMyNotes(true)}
                    className="p-1.5 text-slate-500 hover:text-slate-300 rounded-lg transition-colors duration-150"
                    title="Edit"
                    aria-label="Edit personal notes"
                  >
                    <Pencil size={14} />
                  </button>
                )}
              </div>
              {editingMyNotes ? (
                <MeetingNotesEditor
                  value={meeting.myNotesMarkdown}
                  onSave={handleSaveMyNotes}
                  onCancel={() => setEditingMyNotes(false)}
                />
              ) : hasMyNotes ? (
                <div className="text-sm text-slate-300 whitespace-pre-wrap leading-relaxed">
                  {meeting.myNotesMarkdown}
                </div>
              ) : (
                <p className="text-sm text-slate-500 italic">
                  No personal notes. Click edit to add.
                </p>
              )}
            </section>

            {/* Transcript segments */}
            {hasTranscript && (
              <section className="p-5 sm:p-6 space-y-3">
                <h3 className="text-sm font-semibold text-slate-300">
                  Transcript
                </h3>
                <div className="space-y-3 max-h-96 overflow-y-auto pr-1">
                  {meeting.transcriptSegments.map((seg) => (
                    <TranscriptSegment key={seg.id} seg={seg} />
                  ))}
                </div>
              </section>
            )}

            {/* Fallback: raw transcript text */}
            {!hasTranscript && meeting.transcript && (
              <section className="p-5 sm:p-6 space-y-3">
                <h3 className="text-sm font-semibold text-slate-300">
                  Transcript
                </h3>
                <p className="text-sm text-slate-300 whitespace-pre-wrap leading-relaxed max-h-72 overflow-y-auto">
                  {meeting.transcript}
                </p>
              </section>
            )}
          </div>
        )}
      </article>

      <DeleteMeetingDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        onConfirm={handleDelete}
        isDeleting={isDeleting}
      />
    </>
  );
}
