"use client";

import { useState } from "react";
import {
  Users,
  Calendar,
  ChevronDown,
  ChevronUp,
  MonitorPlay,
  Mic2,
  Copy,
  Mail,
  Pencil,
  MoreVertical,
  Trash2,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";
import { MeetingNotesEditor } from "./MeetingNotesEditor";
import { MeetingMetadataEditor } from "./MeetingMetadataEditor";
import { DeleteMeetingDialog } from "./DeleteMeetingDialog";
import { MarkdownView } from "./MarkdownView";
import { copyMarkdownAsRichText } from "@oscar/shared";
import { ShareDialog } from "@/components/org/ShareDialog";
import type {
  SavedMeetingRecord,
  MeetingTranscriptSegment,
  MeetingAttendee,
  MeetingTypeHint,
} from "@oscar/shared/types";

// ── helpers ──────────────────────────────────────────────────────────────────

function stripCitationTokens(markdown: string): string {
  return markdown
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s*\[\[seg:[A-Za-z0-9._:-]+\]\]/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .trim();
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function meetingTypeBadge(hint: string) {
  const map: Record<string, { label: string }> = {
    discovery: { label: "Discovery" },
    "1on1": { label: "1-on-1" },
    standup: { label: "Stand-up" },
    general: { label: "General" },
    auto: { label: "Meeting" },
  };
  const { label } = map[hint] ?? map.auto;
  return (
    <span
      className="inline-flex items-center px-2 py-0.5 rounded-full text-[0.7rem] font-medium"
      style={{
        fontFamily: '"IBM Plex Mono", ui-monospace, monospace',
        letterSpacing: "0.16em",
        textTransform: "uppercase",
        fontSize: 10,
        color: "#b8623d",
        background: "rgba(184,98,61,0.10)",
      }}
    >
      {label}
    </span>
  );
}

function TranscriptSegment({ seg }: { seg: MeetingTranscriptSegment }) {
  const isSpeaker = seg.speaker.source === "speaker";
  return (
    <div className={`flex gap-3 ${isSpeaker ? "flex-row-reverse" : ""}`}>
      <div className="flex-shrink-0 mt-0.5">
        {isSpeaker ? (
          <MonitorPlay size={14} style={{ color: "#b8623d" }} />
        ) : (
          <Mic2 size={14} style={{ color: "#8b8780" }} />
        )}
      </div>
      <p
        className={`text-sm leading-relaxed max-w-[85%] ${isSpeaker ? "text-right" : ""}`}
        style={{ color: "#1a1816" }}
      >
        <span className="text-[0.65rem] mr-1.5" style={{ color: "#8b8780" }}>
          {seg.speaker.diarization_label ?? (isSpeaker ? "Them" : "Me")}
        </span>
        {seg.text}
      </p>
    </div>
  );
}

// ── types ────────────────────────────────────────────────────────────────────

interface MeetingCardProps {
  meeting: SavedMeetingRecord;
  onUpdate: (
    id: string,
    updates: Partial<SavedMeetingRecord>
  ) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
}

// ── component ────────────────────────────────────────────────────────────────

export function MeetingCard({ meeting, onUpdate, onDelete }: MeetingCardProps) {
  const { toast } = useToast();
  const [expanded, setExpanded] = useState(false);
  const [editingNotes, setEditingNotes] = useState(false);
  const [editingMyNotes, setEditingMyNotes] = useState(false);
  const [editingMetadata, setEditingMetadata] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  const hasTranscript = meeting.transcriptSegments.length > 0;
  const hasNotes = !!meeting.notesMarkdown?.trim();
  const hasMyNotes = !!meeting.myNotesMarkdown?.trim();

  async function handleCopy(text: string) {
    await copyMarkdownAsRichText(text);
    toast({ title: "Copied!", description: "Notes copied to clipboard." });
  }

  function handleEmail() {
    const emails = meeting.attendeesFull
      .map((a) => a.email?.trim())
      .filter(Boolean)
      .join(",");
    const subject = encodeURIComponent(
      `Meeting Notes: ${meeting.meetingTitle || "Untitled"}`
    );
    const body = encodeURIComponent(
      `Hi,\n\nPlease find the meeting notes below.\n\n---\n\n${stripCitationTokens(meeting.notesMarkdown || "")}\n\n---\n\nGenerated by OSCAR`
    );
    window.open(`mailto:${emails}?subject=${subject}&body=${body}`);
  }

  async function handleSaveNotes(value: string) {
    await onUpdate(meeting.id, { notesMarkdown: value });
    setEditingNotes(false);
    toast({ title: "Saved", description: "Meeting notes updated." });
  }

  async function handleSaveMyNotes(value: string) {
    await onUpdate(meeting.id, { myNotesMarkdown: value });
    setEditingMyNotes(false);
    toast({ title: "Saved", description: "Personal notes updated." });
  }

  async function handleSaveMetadata(data: {
    meetingTitle: string;
    attendeesCompact: string;
    attendeesFull: MeetingAttendee[];
    meetingTypeHint: MeetingTypeHint;
  }) {
    await onUpdate(meeting.id, data);
    setEditingMetadata(false);
    toast({ title: "Saved", description: "Meeting details updated." });
  }

  async function handleDelete() {
    setIsDeleting(true);
    try {
      await onDelete(meeting.id);
      toast({ title: "Deleted", description: "Meeting removed." });
    } finally {
      setIsDeleting(false);
      setDeleteOpen(false);
    }
  }

  return (
    <>
      <article
        className="rounded-2xl overflow-hidden transition-all duration-200"
        style={{ background: "#efeae0", border: "1px solid #e5e0d6" }}
      >
        {/* Card header */}
        <div className="flex items-start gap-2">
          <button
            onClick={() => setExpanded((v) => !v)}
            className="flex-1 text-left p-5 sm:p-6 flex items-start justify-between gap-4 group transition-colors duration-150"
            aria-expanded={expanded}
          >
            <div className="min-w-0 flex-1 space-y-2">
              <div className="flex flex-wrap items-center gap-2">
                {meetingTypeBadge(meeting.meetingTypeHint)}
              </div>
              <h2
                className="leading-snug"
                style={{
                  fontFamily: '"EB Garamond", Georgia, serif',
                  fontSize: 22,
                  fontWeight: 500,
                  letterSpacing: "-0.01em",
                  color: "#1a1816",
                }}
              >
                {meeting.meetingTitle || "Untitled Meeting"}
              </h2>
              <div
                className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm"
                style={{ color: "#5a5852" }}
              >
                <span className="flex items-center gap-1.5">
                  <Calendar size={13} className="flex-shrink-0" />
                  {formatDate(meeting.startedAt)}
                </span>
                {meeting.attendeesCompact && (
                  <span className="flex items-center gap-1.5 truncate max-w-[220px]">
                    <Users size={13} className="flex-shrink-0" />
                    {meeting.attendeesCompact}
                  </span>
                )}
              </div>
            </div>
            <div
              className="flex-shrink-0 transition-colors mt-1"
              style={{ color: "#8b8780" }}
            >
              {expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
            </div>
          </button>

          {/* Share + actions */}
          <div className="pt-5 pr-3 sm:pr-4 flex items-start gap-1">
            <ShareDialog
              kind="meeting"
              id={meeting.id}
              visibility={
                meeting.visibility ??
                (meeting.sharedWithOrg ? "org" : "private")
              }
              publicShareToken={meeting.publicShareToken ?? null}
              onChange={(next) =>
                void onUpdate(meeting.id, {
                  visibility: next.visibility,
                  publicShareToken: next.public_share_token,
                  sharedWithOrg: next.visibility !== "private",
                })
              }
            />
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <button
                  className="p-1.5 rounded-full transition-colors duration-150"
                  style={{ color: "#8b8780" }}
                  aria-label="Meeting actions"
                >
                  <MoreVertical size={16} />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent
                align="end"
                style={{ background: "#f7f4ee", border: "1px solid #e5e0d6", color: "#1a1816" }}
              >
                <DropdownMenuItem
                  onClick={() => {
                    setExpanded(true);
                    setEditingMetadata(true);
                  }}
                  className="cursor-pointer"
                  style={{ color: "#1a1816" }}
                >
                  <Pencil size={14} className="mr-2" />
                  Edit details
                </DropdownMenuItem>
                {hasNotes && (
                  <DropdownMenuItem
                    onClick={() => handleCopy(meeting.notesMarkdown)}
                    className="cursor-pointer"
                    style={{ color: "#1a1816" }}
                  >
                    <Copy size={14} className="mr-2" />
                    Copy notes
                  </DropdownMenuItem>
                )}
                {hasNotes && (
                  <DropdownMenuItem
                    onClick={handleEmail}
                    className="cursor-pointer"
                    style={{ color: "#1a1816" }}
                  >
                    <Mail size={14} className="mr-2" />
                    Email notes
                  </DropdownMenuItem>
                )}
                <DropdownMenuItem
                  onClick={() => setDeleteOpen(true)}
                  className="cursor-pointer"
                  style={{ color: "#b8623d" }}
                >
                  <Trash2 size={14} className="mr-2" />
                  Delete
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>

        {/* Metadata editor */}
        {expanded && editingMetadata && (
          <MeetingMetadataEditor
            title={meeting.meetingTitle}
            attendees={meeting.attendeesFull}
            typeHint={meeting.meetingTypeHint}
            onSave={handleSaveMetadata}
            onCancel={() => setEditingMetadata(false)}
          />
        )}

        {/* Expandable body */}
        {expanded && (
          <div style={{ borderTop: "1px solid #e5e0d6" }}>
            {/* AI-generated meeting notes */}
            <section className="p-5 sm:p-6 space-y-3" style={{ borderBottom: "1px solid #e5e0d6" }}>
              <div className="flex items-center justify-between">
                <h3
                  className="text-sm font-semibold"
                  style={{
                    fontFamily: '"IBM Plex Mono", ui-monospace, monospace',
                    letterSpacing: "0.18em",
                    textTransform: "uppercase",
                    color: "#b8623d",
                    fontSize: 10,
                  }}
                >
                  MEETING NOTES
                </h3>
                <div className="flex items-center gap-1">
                  {hasNotes && !editingNotes && (
                    <>
                      <button
                        onClick={() => handleCopy(meeting.notesMarkdown)}
                        className="p-1.5 rounded-full transition-colors duration-150"
                        style={{ color: "#8b8780" }}
                        title="Copy"
                        aria-label="Copy notes"
                      >
                        <Copy size={14} />
                      </button>
                      <button
                        onClick={handleEmail}
                        className="p-1.5 rounded-full transition-colors duration-150"
                        style={{ color: "#8b8780" }}
                        title="Email"
                        aria-label="Email notes"
                      >
                        <Mail size={14} />
                      </button>
                    </>
                  )}
                  {!editingNotes && (
                    <button
                      onClick={() => setEditingNotes(true)}
                      className="p-1.5 rounded-full transition-colors duration-150"
                      style={{ color: "#8b8780" }}
                      title="Edit"
                      aria-label="Edit meeting notes"
                    >
                      <Pencil size={14} />
                    </button>
                  )}
                </div>
              </div>
              {editingNotes ? (
                <MeetingNotesEditor
                  value={stripCitationTokens(meeting.notesMarkdown)}
                  onSave={handleSaveNotes}
                  onCancel={() => setEditingNotes(false)}
                />
              ) : hasNotes ? (
                <div style={{ color: "#1a1816" }}>
                  <MarkdownView>{meeting.notesMarkdown}</MarkdownView>
                </div>
              ) : (
                <p className="text-sm italic" style={{ color: "#8b8780" }}>
                  No AI notes yet. Click edit to add notes.
                </p>
              )}
            </section>

            {/* My personal notes */}
            <section className="p-5 sm:p-6 space-y-3" style={{ borderBottom: "1px solid #e5e0d6" }}>
              <div className="flex items-center justify-between">
                <h3
                  className="text-sm font-semibold"
                  style={{
                    fontFamily: '"IBM Plex Mono", ui-monospace, monospace',
                    letterSpacing: "0.18em",
                    textTransform: "uppercase",
                    color: "#8b8780",
                    fontSize: 10,
                  }}
                >
                  MY NOTES
                </h3>
                {!editingMyNotes && (
                  <button
                    onClick={() => setEditingMyNotes(true)}
                    className="p-1.5 rounded-full transition-colors duration-150"
                    style={{ color: "#8b8780" }}
                    title="Edit"
                    aria-label="Edit personal notes"
                  >
                    <Pencil size={14} />
                  </button>
                )}
              </div>
              {editingMyNotes ? (
                <MeetingNotesEditor
                  value={meeting.myNotesMarkdown}
                  onSave={handleSaveMyNotes}
                  onCancel={() => setEditingMyNotes(false)}
                />
              ) : hasMyNotes ? (
                <div className="prose prose-sm max-w-none leading-relaxed" style={{ color: "#1a1816" }}>
                  <MarkdownView>{meeting.myNotesMarkdown}</MarkdownView>
                </div>
              ) : (
                <p className="text-sm italic" style={{ color: "#8b8780" }}>
                  No personal notes. Click edit to add.
                </p>
              )}
            </section>

            {/* Transcript segments */}
            {hasTranscript && (
              <section className="p-5 sm:p-6 space-y-3">
                <h3
                  className="text-sm font-semibold"
                  style={{
                    fontFamily: '"IBM Plex Mono", ui-monospace, monospace',
                    letterSpacing: "0.18em",
                    textTransform: "uppercase",
                    color: "#8b8780",
                    fontSize: 10,
                  }}
                >
                  TRANSCRIPT
                </h3>
                <div className="space-y-3 max-h-96 overflow-y-auto pr-1">
                  {meeting.transcriptSegments.map((seg) => (
                    <TranscriptSegment key={seg.id} seg={seg} />
                  ))}
                </div>
              </section>
            )}

            {/* Fallback: raw transcript text */}
            {!hasTranscript && meeting.transcript && (
              <section className="p-5 sm:p-6 space-y-3">
                <h3
                  className="text-sm font-semibold"
                  style={{
                    fontFamily: '"IBM Plex Mono", ui-monospace, monospace',
                    letterSpacing: "0.18em",
                    textTransform: "uppercase",
                    color: "#8b8780",
                    fontSize: 10,
                  }}
                >
                  TRANSCRIPT
                </h3>
                <p
                  className="text-sm whitespace-pre-wrap leading-relaxed max-h-72 overflow-y-auto"
                  style={{ color: "#1a1816" }}
                >
                  {meeting.transcript}
                </p>
              </section>
            )}
          </div>
        )}
      </article>

      <DeleteMeetingDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        onConfirm={handleDelete}
        isDeleting={isDeleting}
      />
    </>
  );
}
