-- ── Meetings (Oscar Minutes) ────────────────────────────────────────────────
-- Persists meeting notes generated by the Minutes tab in the desktop app.

create table if not exists public.meetings (
  id            text primary key,                                      -- client-generated id (meeting_<ts>_<rand>)
  user_id       uuid not null references auth.users(id) on delete cascade,
  title         text not null default '',
  date          timestamptz not null default now(),
  participants  text[] not null default '{}',
  transcript    text not null default '',
  notes         text not null default '',
  template_id   text not null default 'meeting_general',
  created_at    timestamptz not null default now()
);

-- RLS: users can only see/modify their own meetings
alter table public.meetings enable row level security;

create policy "owner_select" on public.meetings
  for select using (auth.uid() = user_id);

create policy "owner_insert" on public.meetings
  for insert with check (auth.uid() = user_id);

create policy "owner_delete" on public.meetings
  for delete using (auth.uid() = user_id);
